---
- name: Copy and start service playbook
  hosts: ec2
  become: true
  vars:
    jar_file_path: "/var/lib/jenkins/workspace/aws-deployment-pipeline/target/spark-lms-0.0.1-SNAPSHOT.jar"
    excute_path: "/home/ec2-user/spark-lms-0.0.1-SNAPSHOT.jar"
  tasks:
    - name: Copy JAR file to slave
      copy:
        src: "{{ jar_file_path }}"
        dest: "/home/ec2-user"
        mode: 0644
      register: copy_result

    - name: Install Java 11 Amazon Corretto development package
      dnf:
        name: java-11-amazon-corretto-devel
        state: present

    - name: Create systemd service for Spark LMS
      template:
        src: spark-lms.service.j2
        dest: /etc/systemd/system/spark-lms.service
      notify:
        - Restart Spark LMS service

    - name: Reload systemd manager configuration
      command: "systemctl daemon-reload"
      

    - name: Stop and disable Spark LMS service
      systemd:
        name: spark-lms
        state: stopped
        
     

    - name: Start and enable Spark LMS service
      systemd:
        name: spark-lms
        state: started
        enabled: yes
  handlers:
    - name: Restart Spark LMS service
      systemd:
        name: spark-lms
        state: restarted     


