---
- name: Modify application.properties content
  hosts: ec2
  become: true
  gather_facts: false

  vars:
    DB_URL: "{{ lookup('env', 'DB_URL') }}"
    DB_USERNAME: "{{ lookup('env', 'DB_USERNAME') }}"
    DB_PASSWORD: "{{ lookup('env', 'DB_PASSWORD') }}"
    WORKSPACE_PATH: "/var/lib/jenkins/workspace/aws-deployment-pipeline"

  tasks:
    - name: Update application.properties (DB_URL)
      become: true
      become_user: ec2-user
      lineinfile:
        path: "{{ WORKSPACE_PATH }}/src/main/resources/application.properties"
        regexp: '^spring\.datasource\.url =.*'
        line: "spring.datasource.url = {{ DB_URL }}"

    - name: Update application.properties (DB_USERNAME)
      become: true
      become_user: ec2-user
      lineinfile:
        path: "{{ WORKSPACE_PATH }}/src/main/resources/application.properties"
        regexp: '^spring\.datasource\.username =.*'
        line: "spring.datasource.username = {{ DB_USERNAME }}"

    - name: Update application.properties (DB_PASSWORD)
      become: true
      become_user: ec2-user
      lineinfile:
        path: "{{ WORKSPACE_PATH }}/src/main/resources/application.properties"
        regexp: '^spring\.datasource\.password =.*'
        line: "spring.datasource.password = {{ DB_PASSWORD }}"
